
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftIMPLICATIONDOUBLEIMPLICATIONleftORANDrightNEGATIONAND CONSTANTS DOUBLEIMPLICATION IMPLICATION LPAREN NEGATION OR PROPOSITION PUNCTUATION RPARENexpr : NEGATION exprexpr : expr AND exprexpr : expr OR exprexpr : expr IMPLICATION exprexpr : expr DOUBLEIMPLICATION exprexpr : PROPOSITIONexpr : CONSTANTSexpr : LPAREN expr RPAREN'
    
_lr_action_items = {'NEGATION':([0,2,5,6,7,8,9,],[2,2,2,2,2,2,2,]),'PROPOSITION':([0,2,5,6,7,8,9,],[3,3,3,3,3,3,3,]),'CONSTANTS':([0,2,5,6,7,8,9,],[4,4,4,4,4,4,4,]),'LPAREN':([0,2,5,6,7,8,9,],[5,5,5,5,5,5,5,]),'$end':([1,3,4,10,12,13,14,15,16,],[0,-6,-7,-1,-2,-3,-4,-5,-8,]),'AND':([1,3,4,10,11,12,13,14,15,16,],[6,-6,-7,-1,6,-2,-3,6,6,-8,]),'OR':([1,3,4,10,11,12,13,14,15,16,],[7,-6,-7,-1,7,-2,-3,7,7,-8,]),'IMPLICATION':([1,3,4,10,11,12,13,14,15,16,],[8,-6,-7,-1,8,-2,-3,-4,-5,-8,]),'DOUBLEIMPLICATION':([1,3,4,10,11,12,13,14,15,16,],[9,-6,-7,-1,9,-2,-3,-4,-5,-8,]),'RPAREN':([3,4,10,11,12,13,14,15,16,],[-6,-7,-1,16,-2,-3,-4,-5,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([0,2,5,6,7,8,9,],[1,10,11,12,13,14,15,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expr","S'",1,None,None,None),
  ('expr -> NEGATION expr','expr',2,'p_NEGATION','main.py',50),
  ('expr -> expr AND expr','expr',3,'p_AND','main.py',57),
  ('expr -> expr OR expr','expr',3,'p_OR','main.py',63),
  ('expr -> expr IMPLICATION expr','expr',3,'p_IMPLICATION','main.py',69),
  ('expr -> expr DOUBLEIMPLICATION expr','expr',3,'p_DOUBLEIMPLICATION','main.py',75),
  ('expr -> PROPOSITION','expr',1,'p_expr2PROP','main.py',81),
  ('expr -> CONSTANTS','expr',1,'p_expr2CONST','main.py',87),
  ('expr -> LPAREN expr RPAREN','expr',3,'p_parens','main.py',95),
]
